### ISSUE TITLE
what is the relation with the task dump in the tokio src?

### ISSUE THREAD

**Issue by inevity** [tokio-rs/async-backtrace#31]
see title

**Comment by jswrenn** [comment]
I apologize for the slow response — I was on an extended leave from work.

Both mechanisms are part of a number of experiments I've done for capturing async backtraces. Tokio task dumps are perhaps a little more experimental (bug reports are welcome!). To summarize their differences...

## async-backtrace
- library-only; does not require special async runtime support
- only futures annotated with `#[framed]` appear in async backtraces
- adds a negligible performance overhead to all futures
- requesting an async trace is computationally cheap

## tokio task dump traces
- runtime-supported; libraries don't have to do anything
- virtually all call frames are included in task traces; no special annotations are necessary
- virtually no performance overhead to futures in normal operation
- requesting a trace is computationally expensive
